### PR TITLE
Standalone routes

### LINKED ISSUE #136: How to set all admin routes under /admin?
Currently, the routes generated by the package are all under the main path, but, ideally, all Admin routes should be under /admin, such as /admin/roles, /admin/users, etc. This way, the root routes are free to be used by the main website.

### PR DESCRIPTION
**Pull request by igorsantos07**
This sort of fixes #136.

### CODE REVIEW

**Comment by PovilasKorop** [comment]
@igorsantos07 not an elegant (or easy to understand) solution with standalone routes, but it fixes the problem I guess, so accepting.

**Comment by igorsantos07** [comment]
I tried to give some instructions on the config file... I think that, if the developer is looking for a way to tweak the routes, they'll understand what that option is for :)
Otherwise they can surely ignore it altogether.

Finally, a google search may bring them to #136, from there into this pull request, and they'll find what to do.

**Comment by EdvardasP** [comment]
Hello Guys,

What is ` 'standaloneRoutes'`? It is Laravel thing? Never seen before.

**Comment by PovilasKorop** [comment]
@EdvardasP this is a function added by @igorsantos07 - see documentation for how it works: 

```
// If set to true, you'll need to copy the routes
// from vendor/laraveldaily/quickadmin/src/routes.php into your own /routes folder
'standaloneRoutes'   => false
```

https://github.com/LaravelDaily/quickadmin/pull/139/commits/fe6f8aae49ac87aecb67bd80417dc573c0226615

**Comment by EdvardasP** [comment]
Thank you, Povilas :)

**Pull request merged**
