### PR TITLE
Decoupling auth from the package

### PR DESCRIPTION
**Pull request by Jeroen-G**
This is most likely a starting point for solving issue #9, not entirely sure if it brings up bugs as it is at the moment.

### CODE REVIEW

**Comment by PovilasKorop** [comment]
Wow, @Jeroen-G - huge thanks for the help! To be honest, this decoupling wasn't in our priorities, cause we wanted to make QuickAdmin work best in the simple specific case of Fresh Laravel + Auth + Quickadmin + CRUD creation (i.e. without external roles functionality), so we will analyze your changes a little deeper before merging. But on the surface it looks good.

**Comment by Jeroen-G** [comment]
I get that, but for me it is a high priority because otherwise I cannot use it. :smile:

**Comment by PovilasKorop** [comment]
Oh ok, we will speed it up :)

**Comment by Jeroen-G** [comment]
I spotted a few bugs myself, I will commit them later today.

**Comment by PovilasKorop** [comment]
Thank you, we are still in bug-fixing mode with this package. That's why it's still 0.2 version.

**Comment by PovilasKorop** [comment]
Ok, analyzed your code @Jeroen-G - you see, the problem is that it adds additional step to install and potentially additional complexity for users (we are aiming at mass-market, so not all less-experienced devs will know what Bridge is and how to update it). So potentially for our package idea it's quite a huge step to the side or even back.
Do you think it's possible that you would fork the package to use it for your needs? Or use it as it is now to generate CRUDs, and then add your permissions functionality on top?

**Comment by Jeroen-G** [comment]
Okay, I suppose I can work with a fork.

**Pull request closed without merging**
